# Generated by Django 4.2.6 on 2023-11-22 21:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_alter_user_email_alter_user_username'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='image',
            field=models.ImageField(default='profiles/defaultprofile.jpeg', upload_to='profiles/'),
        ),
    ]
