# Generated by Django 4.2.6 on 2023-12-05 23:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_alter_profile_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Article_title', models.CharField(max_length=200)),
                ('Article_summary', models.CharField(max_length=200)),
                ('Article_category', models.CharField(max_length=200)),
                ('Article_date', models.DateField()),
            ],
        ),
    ]
