# Generated by Django 4.2.6 on 2023-12-12 22:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_remove_comment_article_remove_comment_parent_comment_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='article',
            name='Comments',
        ),
        migrations.RemoveField(
            model_name='comment',
            name='children_comments',
        ),
        migrations.AddField(
            model_name='comment',
            name='article',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='api.article'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='comment',
            name='parent_comment',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='api.comment'),
        ),
    ]
