# Generated by Django 4.2.6 on 2023-12-13 15:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_remove_article_comments_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(choices=[('Sports', 'Sports'), ('World News', 'World News'), ('Technology', 'Technology'), ('Health & Wellness', 'Health & Wellness'), ('Entertainment', 'Entertainment')], max_length=100, unique=True)),
            ],
        ),
        migrations.AddField(
            model_name='profile',
            name='date_of_birth',
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='favorite_categories',
            field=models.ManyToManyField(to='api.category'),
        ),
        migrations.AlterField(
            model_name='article',
            name='Article_category',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.category'),
        ),
    ]
